CREATE TABLE ADMGT_AD_IDS_TB(PK_AD_ID INT IDENTITY(1,1) PRIMARY KEY,FK_AD_IDS_LOGIN VARCHAR(20)REFERENCES ADMGT_LOGIN_TB(PK_LOGIN_USER_NAME),FK_AD_IDS_DURATION VARCHAR(10)REFERENCES ADMGT_DURATION_TB(PK_DURA_DID),RECOMMENDATIONS VARCHAR(40) , NUM_TIMES int,TOTAL_PRICE money)

