
create table ADMGT_BUDGET_TB(BUDGET MONEY,PK_BUDGET_START_DATE DATETIME PRIMARY KEY,END_DATE DATETIME)
INSERT INTO ADMGT_BUDGET_TB VALUES (13000,'2006/11/23','2006/11/24')
select * from ADMGT_BUDGET_TB


